kind: Deployment
apiVersion: apps/v1
metadata:
  name: pod-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-controller
  template:
    metadata:
      labels:
        app: pod-controller
    spec:
      serviceAccount: pod-controller-sv
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: custom-controller
          image: shahra/custom-controller:latest
          imagePullPolicy: "Never"
          args:
            - "--only-respond-to-annotation=true"